# Habilitar actualizaciones automáticas
auto-update: true

# Se agregó progresión personalizada al menú de progresión básico. (Funciones experimentales)
use-advancements-api: true

# Mostrar mensaje de progreso en la barra de chat
announce-advancements: true

# Si se debe agregar un botón de progreso de tecnología de limo a la guía de tecnología de limo
add-advancements-to-guide: true

# Ya sea para generar registros de depuración
debug: false

# Ya sea para ejecutar después de eliminar el progreso Bukkit.reloadData (Puede causar retraso)
reload-data-on-adv-remove: true
